name: Generate and Process Report

on:
  workflow_dispatch:
    inputs:
      api_key:
        description: 'API key of user'
        required: true
        type: string
        default: 'report' #Optional default value
      project_id:
        description: 'Id of project'
        required: true
        type: string

jobs:
  process_report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      continue-on-error: true
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
          version: '9.6.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuitePath="Test Suites/healthcare-tests - TS_RegressionTest" -browserType="Chrome" -apiKey="${{ github.event.inputs.api_key }}" --config -webui.autoUpdateDrivers=true'
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: all-reports-${{ github.run_id }}
        path: Reports
        retention-days: 5
    
  upload_report:
    runs-on: ubuntu-latest
    needs: process_report
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v4
        with:
          name: all-reports-${{ github.run_id }}
          path: processed_reports
          
      - name: Katalon Report Uploader
        uses: katalon-studio/report-uploader@v0.0.8
        env:
          PASSWORD: ${{ github.event.inputs.api_key }}
          PROJECT_ID: ${{ github.event.inputs.project_id }}
          TYPE: katalon
          REPORT_PATH: processed_reports
